class AppIcons():
    MAIN_APP = ":material/book_4_spark:"
    #Notification
    ERROR = ":material/error:"
    WARNING = ":material/warning:"
    SUCCESS =":material/check_circle:"
    #Menu
    HOME_PAGE = ":material/home:"
    MENU_PAGE = ":material/menu:"
    INSERT_PAGE = ":material/add:"
    EXPORT_PAGE = ":material/download:"
    DASHBOARD_PAGE = ":material/empty_dashboard:"
    MANAGE_PAGE = ":material/lists:"
    BUG_REPORT_PAGE = ":material/bug_report:"
    LOGIN_PAGE = ":material/account_circle:"
    REPO_PAGE = ":material/bookmark:"
    DATA_FRAME = ":material/description:"
    #Button
    SEND_EMAIL = ":material/send:"
    MAIL = ":material/mail:"
    LOG_IN = ":material/input:"
    LOG_OUT = ":material/exit_to_app:"
    SAVE = ":material/save_as:"
    SYNC = ":material/sync:"
    METRICS = ":material/monitoring:"
    LINE_CHART = ":material/area_chart:"
    BAR_CHART = ":material/insert_chart:"
    PIE_CHART = ":material/pie_chart:"
    HEAT_MAP = ":material/key_visualizer:"
    VIETNAMESE =":flag-vi:"
    ENGLISH =":flag-us:"
    