class AppIcons:
    ERROR = ":material/error:"
    HOME = ":material/home:"
    WARNING = ":material/warning:"
    MENU = ":material/menu:"
    INSERT = ":material/add_task:"
    DASHBOARD = ":material/empty_dashboard:"
    MANAGE = ":material/lists:"
    BUG_REPORT = ":material/bug_report:"
    #Button
    SEND_EMAIL = ":material/send:"
    MAIL = ":material/mail:"
    LOG_IN = ":material/input:"
    LOG_OUT = ":material/exit_to_app:"
    SAVE = ":material/save_as:"
    SYNC = ":material/sync:"